model_name_or_path: facebook/bart-large
checkpoint_to_load: exp/bart_large_tr3/checkpoint-1
do_train: true
do_eval: true
output_dir: exp/bart_large_tr3r_v2
per_device_train_batch_size: 64
per_device_eval_batch_size: 32
gradient_accumulation_steps: 1
overwrite_output_dir: true
predict_with_generate: true
train_file: data/train-reminder-25spis/data.json
validation_file: data/valid-reminder-25spis/data.json
save_strategy: epoch
evaluation_strategy: epoch
num_train_epochs: 200
add_special_vocab: true
learning_rate: 0.00001
warmup_steps: 100
label_smoothing_factor: 0.1
save_total_limit: 1
