model_name_or_path: facebook/bart-large
checkpoint_to_load: exp/bart_large_tr3/checkpoint-1
do_train: true
do_eval: true
output_dir: exp/bart_large_tr3w_v2_aug10x1m0.2th0
per_device_train_batch_size: 64
per_device_eval_batch_size: 32
gradient_accumulation_steps: 1
overwrite_output_dir: true
predict_with_generate: true
train_file: data/train-weather-25spis/data_aug10x1m0.20_th0.00.json
validation_file: data/valid-weather-25spis/data.json
save_strategy: epoch
evaluation_strategy: epoch
num_train_epochs: 50
add_special_vocab: true
learning_rate: 0.00001
warmup_steps: 500
label_smoothing_factor: 0.1
save_total_limit: 1
