model_name_or_path: facebook/bart-large
do_train: true
do_eval: true
output_dir: exp/bart_large_tr3_retro_v2/
per_device_train_batch_size: 50
per_device_eval_batch_size: 32
gradient_accumulation_steps: 5
overwrite_output_dir: true
predict_with_generate: true
train_file: data/train-tr3/data_retro__p0.10_cat4_x30.json
validation_file: data/valid-tr3/data_retro__cat4.json
save_strategy: steps
evaluation_strategy: steps
num_train_epochs: 1
add_special_vocab: true
learning_rate: 0.00001
warmup_steps: 5000
label_smoothing_factor: 0.1
save_total_limit: 1
