model_name_or_path: facebook/bart-large
checkpoint_to_load: exp/bart_large_tr3_retro_v2/checkpoint-1
do_train: true
do_eval: true
output_dir: exp/bart_large_tr3r_retro_aug10x1m0.2th0_v2_fix
per_device_train_batch_size: 50
per_device_eval_batch_size: 32
gradient_accumulation_steps: 1
overwrite_output_dir: true
predict_with_generate: true
train_file: data/train-reminder-25spis/data_aug10x1m0.20_th0.00_retro__p0.10_cat4_x10.json
validation_file: data/valid-reminder-25spis/data_retro__cat4.json
save_strategy: epoch
evaluation_strategy: epoch
num_train_epochs: 5
add_special_vocab: true
learning_rate: 0.00001
warmup_steps: 500
label_smoothing_factor: 0.1
save_total_limit: 10
