model_name_or_path: facebook/bart-large
do_train: true
do_eval: true
do_predict: true
output_dir: exp/bart_large_v2/
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
gradient_accumulation_steps: 12
overwrite_output_dir: true
predict_with_generate: true
train_file: data/train/data.json
validation_file: data/valid/data.json
test_file: data/test/data.json
evaluation_strategy: epoch
num_train_epochs: 50
add_special_vocab: true
learning_rate: 0.001
warmup_steps: 5000
label_smoothing_factor: 0.1
