freeze_param: [
"frontend.upstream"
]

frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: wavlm_large  # Note: If the upstream is changed, please change the input_size in the preencoder.
    download_dir: ./hub
    multilayer_feature: False
    layer: 12

encoder: conformer
encoder_conf:
    output_size: 1024
    attention_heads: 8
    linear_units: 1024
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d2
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 31

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 512
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.0
    lsm_weight: 0.15
    length_normalized_loss: false
    extract_feats_in_collect_stats: false
    avoid_encoder: true

ctc_conf:
    ignore_nan_grad: true


use_amp: true
num_workers: 4

# This configuration requires Tesla V100-SXM2(32GB) x 8 GPUs It takes about 4 days.
# batch_type: length
# batch_bins: 40000000
batch_type: folded
batch_size: 8
accum_grad: 1
max_epoch: 50

patience: none

init: xavier_uniform 

best_model_criterion:
-   - valid
    - acc
    - max

keep_nbest_models: 5
log_interval: 5000
optim: adam
optim_conf:
    lr: 0.0002
scheduler: reducelronplateau
scheduler_conf: 
    mode: max
    patience: 4
unused_parameters: true
#init_param: ['/scratch/bbjs/chen26/owsm_v3/exp/s2t_train_s2t_transformer_conv2d_size1024_e24_d24_lr2.5e-4_warmup10k_finetune_raw_bpe50000/valid.acc.ave_5best.till50epoch.pth']